changelog:
  exclude:
    labels:
      - ignore-for-release-1
  categories:
    - title: new features 🚀
      labels:
        - enhancement
    - title: bug fixes and improvements ✨
      labels:
        - bug-fix
    - title: other changes 🛠️
      labels:
        - "*"
